### PR TITLE
twind theme fix

### LINKED ISSUE #9: Colors are not rendering
Screenshot 2021-09-15 at 14 17 20
Screenshot 2021-09-15 at 14 18 03
Hey team,
I currently trying Tailwind CSS Design system, however, colors are not working for me. Adding screenshots if its helpful 🙂

### PR DESCRIPTION
**Pull request by mveres**
https://backlight.dev/edit/U3bRwsh0qncQBY27uPGi/colors/src/index.ts?branch=colors-fix@tLlGPKdxk2VRYywCKUXNaV8PFt62

### CODE REVIEW

**Review by gqio — APPROVED** [review]

File: mdx-layout/src/index.tsx [hunk 1]
```diff
@@ -2,6 +2,10 @@ import * as React from 'react';
 import { MDXProvider } from '@mdx-js/react';
 import { CoreLayout } from '@divriots/dockit-react/mdx-layout-core/dist/CoreLayout';
 import '~/all/src/styles.css';
```
Comment (georges-gomes) [inline mdx-layout/src/index.tsx]: you probably want to remove styles.css here because twind does the job
